apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: {{ include "table-name-resource-groups" . }}
spec:
  database: {{ include "db-name" . }}
  name: {{ include "table-name-groups" . }}
  schema:
    postgres:
      columns:
      - name: &id id
        type: text
        constraints:
          notNull: true
      - name: name
        type: text
        constraints:
          notNull: true
      primaryKey:
      - *id