apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: {{ .Values.haExpenseSplitter.db.resourceName }}
spec:
  immediateDeploy: true
  connection:
    postgres:
      dbname:
        value: {{ .Values.haExpenseSplitter.db.name | quote }}
      host:
        value: {{ .Values.haExpenseSplitter.db.host | quote }}
      port:
        value: {{ .Values.haExpenseSplitter.db.port | quote }}
      user:
        valueFrom:
          secretKeyRef:
            name: {{ .Values.haExpenseSplitter.db.adminUser.username.secret.name }}
            key: {{ .Values.haExpenseSplitter.db.adminUser.username.secret.key }}
      {{- if hasKey .Values.haExpenseSplitter.db.adminUser "password" }}
      password:
        valueFrom:
          secretKeyRef:
            name: {{ .Values.haExpenseSplitter.db.adminUser.password.secret.name }}
            key: {{ .Values.haExpenseSplitter.db.adminUser.password.secret.key }}
      {{- end }}