{{- with .Values.haExpenseSplitter.db.adminUser }}
{{- if hasKey .username "value" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .username.secret.name }}
  annotations:
    # we need these for hooks to be able to register the credentials in the DB
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
stringData:
  {{ .username.secret.key }}: {{ .username.value | quote }}
  {{- if and (hasKey  "password") (hasKey .password "value") (eq .username.secret.name .password.secret.name) }}
  {{ .password.secret.key }}: {{ .password.value | quote }}
  {{- end }}
---
{{ if and (hasKey "password") (hasKey .password "value") (ne .username.secret.name .password.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .password.secret.name }}
  annotations:
    # we need these for hooks to be able to register the credentials in the DB
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
stringData:
  {{ .password.secret.key }}: {{ .password.value | quote }}
{{- end }}
{{- end }}
{{- end }}