{{- if hasKey .Values.haExpenseSplitter.db.adminUser "credentials" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.haExpenseSplitter.db.adminUser.secret.name }}
  annotations:
    # we need these for hooks to be able to register the credentials in the DB
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
stringData:
  {{ .Values.haExpenseSplitter.db.adminUser.secret.userKey }}: "{{ .Values.haExpenseSplitter.db.adminUser.credentials.user }}"
  {{ .Values.haExpenseSplitter.db.adminUser.secret.passwordKey }}: "{{ .Values.haExpenseSplitter.db.adminUser.credentials.password }}"
{{- end }}