{{- range $processorName, $processorSpec := .Values.haExpenseSplitter.processors.specs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "processor-name-secret" $processorName }}
stringData:
  {{- if hasKey $processorSpec "db" }}
  {{ include "dbUserKey" . }}: "{{ $processorSpec.db.user }}"
  {{ include "dbPasswordKey" . }}: "{{ $processorSpec.db.password }}"
  {{- end }}
{{- end }}