{{- range $processorName, $processorSpec := .Values.haExpenseSplitter.processors.specs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "processor-name-configMap" $processorName }}
data:
  {{- if hasKey $processorSpec "db" }}
  {{ include "dbNameKey" . }}: "{{ $processorSpec.db.name }}"
  {{ include "dbHostKey" . }}: "{{ $processorSpec.db.host }}"
  {{ include "dbPortKey" . }}: "{{ $processorSpec.db.port }}"
  {{- end }}
{{- end }}