{{- range $processorName, $processorSpec := .Values.haExpenseSplitter.processors.specs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "processor-name-serviceaccount" $processorName }}"
automountServiceAccountToken: true
{{- end }}