{{- range $processorName, $processorSpec := .Values.haExpenseSplitter.processors.specs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "processor-name-secret" $processorName }}
  annotations:
    # we need these for hooks to be able to register the credentials in the DB
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
stringData:
  {{- if $processorSpec.db }}
  {{ include "dbUserKey" . }}: "{{ printf "%s-user" $processorName }}"
  {{ include "dbPasswordKey" . }}: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}