{{- range $serviceName, $serviceSpec := .Values.haExpenseSplitter.services.specs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "service-name-serviceaccount" $serviceName }}"
automountServiceAccountToken: true
{{- end }}