{{- range $serviceName, $serviceSpecs := merge (merge (dict "documentation" .Values.haExpenseSplitter.documentation) .Values.haExpenseSplitter.services.specs) (dict "reflection" .Values.haExpenseSplitter.services.reflection) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-name-secret" $serviceName }}
stringData:
  {{- if hasKey $serviceSpecs "db" }}
  {{ include "service-dbUserKey" . }}: "{{ $serviceSpecs.db.user }}"
  {{ include "service-dbPasswordKey" . }}: "{{ $serviceSpecs.db.password }}"
  {{- end }}
{{- end }}