{{- range $serviceName, $serviceSpecs := merge (merge (dict "documentation" .Values.haExpenseSplitter.documentation) .Values.haExpenseSplitter.services.specs) (dict "reflection" .Values.haExpenseSplitter.services.reflection) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-name-secret" $serviceName }}
  annotations:
    # we need these for hooks to be able to register the credentials in the DB
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
stringData:
  {{- if $serviceSpecs.db }}
  {{ include "dbUserKey" . }}: "{{ printf "%s-user" $serviceName }}"
  {{ include "dbPasswordKey" . }}: {{ randAlphaNum 32 | quote }}
  {{- end }}
{{- end }}