{{- range $serviceName, $serviceSpecs := merge (merge (dict "documentation" .Values.haExpenseSplitter.documentation) .Values.haExpenseSplitter.services.specs) (dict "reflection" .Values.haExpenseSplitter.services.reflection) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-name-configMap" $serviceName }}
data:
  {{ include "service-serverHostnameKey" . }}: "{{ include "service-name" $serviceName }}"
  {{ include "service-serverPortKey" . }}: "{{ include "service-serverPort" . }}"
{{- end }}