# creates DB users for services and processors
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-db-users"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
      {{- include "securitycontext" (dict "primary" .Values.haExpenseSplitter.securityContext) | nindent 6 }}
      containers:
      - name: "create-db-users"
        image: "{{ .Values.haExpenseSplitter.db.image.psql.repository }}:{{ .Values.haExpenseSplitter.db.image.psql.tag }}"
        imagePullPolicy: "IfNotPresent"
        args:
          - my
          - args
          - to
          - psql
          # TODO: create psql users (or overrides existing ones) with the help of the secrets created for services and processors
