{{ if .Values.instanceProfiles }}
{{- range .Values.instanceProfiles }}
---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: {{ .name }}
  {{- if and $.Release.IsInstall $.Values.cluster.create }}
  annotations:
    "helm.sh/hook": pre-install
    "meta.helm.sh/release-name": {{ $.Release.Name }}
    "meta.helm.sh/release-namespace": {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  cpu: "{{ .cpu }}"
  memory: "{{ .memory }}"
  {{- with .hugePages }}
  hugePages:
    {{- with (index . "hugepages-2Mi") }}
    hugepages-2Mi: "{{ . }}"
    {{- end }}
    {{- with (index . "hugepages-1Gi") }}
    hugepages-1Gi: "{{ . }}"
    {{- end }}
  {{- end }}
  {{- if .containers }}
  {{- range $key,$value := .containers }}
  containers:
    {{ $key | quote }}:
      cpu: "{{ .cpu }}"
      memory: "{{ .memory }}"
      {{- with .hugePages }}
      hugePages:
        {{- with (index . "hugepages-2Mi") }}
        hugepages-2Mi: "{{ . }}"
        {{- end }}
        {{- with (index . "hugepages-1Gi") }}
        hugepages-1Gi: "{{ . }}"
        {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if .initContainers }}
  {{- range $key,$value := .initContainers }}
  initContainers:
    {{ $key | quote }}:
      cpu: "{{ .cpu }}"
      memory: "{{ .memory }}"
      {{- with .hugePages }}
      hugePages:
        {{- with (index . "hugepages-2Mi") }}
        hugepages-2Mi: "{{ . }}"
        {{- end }}
        {{- with (index . "hugepages-1Gi") }}
        hugepages-1Gi: "{{ . }}"
        {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}