{{ if and .Values.configurations.create .Values.configurations.poolingconfig.create }}
apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: {{ .Values.cluster.configurations.sgPoolingConfig }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    "helm.sh/hook": pre-install
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  pgBouncer:
    {{- with (index .Values.configurations.poolingconfig.pgBouncer "pgbouncer.ini") }}
    pgbouncer.ini:
      pgbouncer:
      {{- range $key, $value := . }}
        {{ $key }}: '{{ $value }}'
      {{- end }}
    {{- end }}
{{ end }}
