{{- if .Values.cluster.managedSql }}
{{- if hasKey .Values.cluster.managedSql "secretScripts" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-scripts
  annotations:
    # we need these for script hooks to be able to run
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-2"
stringData:
{{- range $scriptName, $script := .Values.cluster.managedSql.secretScripts }}
  {{ $scriptName | quote }}: |
    {{- $script | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}