apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global-name-configMap" . }}
data:
  {{ include "global-globalDomainKey" . }}: "{{ $.Values.global.domain }}"
  {{ include "global-k8sGetRequestErrorReasonKey" . }}: "{{ include "global-k8sGetRequestErrorReason" . }}"
  {{ include "global-natsServerHostKey" . }}: "{{ .Values.haExpenseSplitter.services.nats.server.host }}"
  {{ include "global-natsServerPortKey" . }}: "{{ .Values.haExpenseSplitter.services.nats.server.port }}"
  {{ include "global-traceCollectorHostKey" . }}: "{{ .Values.haExpenseSplitter.services.traceCollector.server.host }}"
  {{ include "global-traceCollectorPortKey" . }}: "{{ .Values.haExpenseSplitter.services.traceCollector.server.port }}"