apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global-name-configMap" . }}
data:
  {{ include "global-globalDomainKey" . }}: "{{ $.Values.global.domain }}"
  {{ include "global-k8sGetRequestErrorReasonKey" . }}: "{{ include "global-k8sGetRequestErrorReason" . }}"
  {{ include "global-natsServerHostKey" . }}: "{{ include "global-natsServerHost" . }}"
  {{ include "global-natsServerPortKey" . }}: "{{ include "global-natsServerPort" . }}"